#!/usr/bin/env python3
"""Train a tiny scikit-learn classifier and export a Dart model file.

This uses pandas, numpy, and scikit-learn for a more recognizable ML workflow:
- load JSONL into a dataframe
- vectorize the synthetic text/action/scenario features
- fit a Multinomial Naive Bayes classifier
- export the learned parameters into Dart for local inference
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

ROOT = Path(__file__).resolve().parents[2]
DATA_FILE = ROOT / "ml" / "data" / "simulator_training_data.jsonl"
OUT_FILE = ROOT / "lib" / "src" / "features" / "simulators" / "domain" / "generated_ml_models.dart"

LABELS = ["dangerous", "at_risk", "good", "excellent"]

def make_feature_text(record: pd.Series) -> str:
    actions = " ".join(f"action_{action}" for action in record["actions"])
    return f"scenario_{record['scenario']} {actions} {record['reply']}"


def load_records() -> pd.DataFrame:
    return pd.read_json(DATA_FILE, lines=True)


def train_domain(df: pd.DataFrame) -> dict[str, object]:
    features = df.apply(make_feature_text, axis=1)
    labels = df["label"]

    vectorizer = CountVectorizer(
        lowercase=True,
        token_pattern=r"[a-z0-9']+",
    )
    x = vectorizer.fit_transform(features)
    classifier = MultinomialNB(alpha=1.0)
    classifier.fit(x, labels)

    vocabulary = vectorizer.get_feature_names_out().tolist()
    label_order = classifier.classes_.tolist()

    feature_log_prob = classifier.feature_log_prob_
    class_log_prior = classifier.class_log_prior_

    likelihoods: dict[str, dict[str, float]] = {}
    for label_index, label in enumerate(label_order):
        likelihoods[label] = {
            token: float(feature_log_prob[label_index, token_index])
            for token_index, token in enumerate(vocabulary)
        }

    class_count = classifier.class_count_
    total_feature_count = classifier.feature_count_.sum(axis=1)
    vocab_size = len(vocabulary)
    unknown_log_prob = {
        label_order[index]: float(np.log(1.0 / (total_feature_count[index] + vocab_size)))
        for index in range(len(label_order))
    }

    priors = {
        label_order[index]: float(class_log_prior[index])
        for index in range(len(label_order))
    }

    return {
        "labels": label_order,
        "priors": priors,
        "likelihoods": likelihoods,
        "unknownLogProb": unknown_log_prob,
        "vocabulary": vocabulary,
    }


def to_dart_map(value: object, indent: int = 0) -> str:
    space = " " * indent
    if isinstance(value, dict):
        items = []
        for key, item in value.items():
            items.append(
                f"{space}  {json.dumps(str(key))}: {to_dart_map(item, indent + 2)},"
            )
        return "{\n" + "\n".join(items) + f"\n{space}" + "}"
    if isinstance(value, list):
        items = [f"{space}  {to_dart_map(item, indent + 2)}," for item in value]
        return "[\n" + "\n".join(items) + f"\n{space}" + "]"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, float):
        return repr(value)
    return str(value)


def write_dart_export(sms_model: dict[str, object], email_model: dict[str, object]) -> None:
    content = f"""// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by tools/ml/train_simulator_model.py

const Map<String, dynamic> generatedSmsMlModel = {to_dart_map(sms_model)};

const Map<String, dynamic> generatedEmailMlModel = {to_dart_map(email_model)};
"""
    OUT_FILE.write_text(content, encoding="utf-8")


def main() -> None:
    if not DATA_FILE.exists():
        raise SystemExit(f"Training data file not found: {DATA_FILE}")

    records = load_records()
    sms_records = records[records["domain"] == "sms"].copy()
    email_records = records[records["domain"] == "email"].copy()

    sms_model = train_domain(sms_records)
    email_model = train_domain(email_records)
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    write_dart_export(sms_model, email_model)
    print(f"Exported model file to {OUT_FILE}")


if __name__ == "__main__":
    main()
