name: cs310_server
description: Serverpod backend for CS310 auth and account storage.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  mailer: ^6.1.0
  serverpod: ^3.2.0
  serverpod_auth_core_server: ^3.2.0
  serverpod_auth_idp_server: ^3.2.0

dev_dependencies:
  lints: ^5.0.0
